# Generated by Django 2.1.7 on 2019-03-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190316_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='GPA',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
