# Generated by Django 2.1.7 on 2019-03-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190320_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='graduation',
            field=models.CharField(choices=[('1', '2019'), ('2', '2020'), ('3', '2021'), ('4', '2022')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.CharField(choices=[('A', '$0~$3000'), ('B', '$3000~$6000'), ('C', '$6000~$10000'), ('D', '$10000~')], default='A', max_length=1),
        ),
    ]
